version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db_dev
    environment:
      MYSQL_ROOT_PASSWORD: root_dev_secure
      MYSQL_DATABASE: dataalign_dev
      MYSQL_USER: dataalign_dev
      MYSQL_PASSWORD: dev_secure_123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"  # Different port for dev
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - dataalign_dev_net
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: dataalign_app_dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+pymysql://dataalign_dev:dev_secure_123@db:3306/dataalign_dev"
      FLASK_ENV: development
      FLASK_DEBUG: true
      AUTO_PDF_GENERATION: "true"
      AUTO_MIGRATION: "true"
    ports:
      - "5006:5000"  # Different port for dev
    volumes:
      - uploads_dev_data:/app/uploads
      - temp_dev_data:/app/temp
      - .:/app  # Mount source code for development
    networks:
      - dataalign_dev_net
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer_dev
    ports:
      - "8081:8080"  # Different port for dev
    networks:
      - dataalign_dev_net
    environment:
      ADMINER_DEFAULT_SERVER: db

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_dev
    ports:
      - "1026:1025"  # SMTP
      - "8026:8025"  # Web interface
    networks:
      - dataalign_dev_net

volumes:
  mysql_dev_data:
  uploads_dev_data:
  temp_dev_data:

networks:
  dataalign_dev_net:
    driver: bridge
