"""Auto migration

Revision ID: 3caf08ce3dfc
Revises: a798736e4cdc
Create Date: 2025-08-07 11:18:24.330288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3caf08ce3dfc'
down_revision = 'a798736e4cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.alter_column('projet_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.alter_column('projet_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
