"""Ajout de date_creation

Revision ID: 611bd9705a03
Revises: 
Create Date: 2025-07-15 09:02:20.675772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611bd9705a03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.drop_column('date_creation')

    # ### end Alembic commands ###
