"""Auto migration

Revision ID: 69c1780de074
Revises: 
Create Date: 2025-07-30 09:59:06.423798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c1780de074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichiers_generes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fichiers_generes_projet'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projets', ['projet_id'], ['id'])

    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('fichiers_generes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_fichiers_generes_projet'), 'projets', ['projet_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
