"""Auto migration

Revision ID: ac1eb72ff16f
Revises: 69c1780de074
Create Date: 2025-07-30 10:00:09.266397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1eb72ff16f'
down_revision = '69c1780de074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichiers_generes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_fichiers_generes_projet'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichiers_generes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('fk_fichiers_generes_projet'), ['projet_id'], unique=False)

    # ### end Alembic commands ###
