"""Auto migration

Revision ID: b98dd7326e2e
Revises: 3caf08ce3dfc
Create Date: 2025-08-07 12:08:58.605493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98dd7326e2e'
down_revision = '3caf08ce3dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fichier_genere_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fichiers_generes', ['fichier_genere_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fichier_genere_id')

    # ### end Alembic commands ###
